CREATE USER SHARK IDENTIFIED BY "SHARK";
GRANT CREATE SESSION TO SHARK;
GRANT CREATE TABLE TO SHARK;
ALTER DATABASE DEFAULT TABLESPACE users;
GRANT UNLIMITED TABLESPACE TO SHARK;

grant CREATE SEQUENCE to SHARK;


