
-- following code is to be executed to create the proper user (local)

--CREATE USER SHARK IDENTIFIED BY "SHARK";
--GRANT CREATE SESSION TO SHARK;
--GRANT CREATE TABLE TO SHARK;
--ALTER DATABASE DEFAULT TABLESPACE users;
--GRANT UNLIMITED TABLESPACE TO SHARK;
--
--grant CREATE SEQUENCE to SHARK;

--

DROP TABLE SHARK.DIVISIONS;
DROP TABLE SHARK.MEMBERS;
DROP TABLE SHARK.LICENSEPLATES;
DROP SEQUENCE SHARK.MEMBERS_SEQ;
DROP SEQUENCE SHARK.DIVISIONS_SEQ;
DROP SEQUENCE SHARK.LICENSEPLATES_SEQ;

CREATE TABLE SHARK.DIVISIONS
   (ID NUMBER NOT NULL ENABLE,
	NAME VARCHAR2(31 CHAR) NOT NULL ENABLE,
	ORIGINALNAME VARCHAR2(31 CHAR) NOT NULL ENABLE,
	DIRECTOR VARCHAR2(31 CHAR) NOT NULL ENABLE,
	PARENTDIVISION NUMBER(5,0),
	 CONSTRAINT DIVISION_PK PRIMARY KEY (ID)
   );

   CREATE SEQUENCE DIVISIONS_SEQ
   START WITH 1
   INCREMENT BY 1;

CREATE TABLE SHARK.LICENSEPLATES
   (ID NUMBER NOT NULL ENABLE,
	PLATE_NUMBER VARCHAR2(31 CHAR) NOT NULL ENABLE,
	ISSUING_COUNTRY VARCHAR2(31 CHAR) NOT NULL ENABLE,
	 CONSTRAINT LICENSEPLATES_PK PRIMARY KEY (ID)
   );

   CREATE SEQUENCE LICENSEPLATES_SEQ
   START WITH 1
   INCREMENT BY 1;

CREATE TABLE SHARK.MEMBERS (
    ID INT PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    STREET_NAME VARCHAR2(255) NOT NULL,
    STREET_NUMBER VARCHAR2(255) NOT NULL,
    POSTAL_CODE VARCHAR2(255) NOT NULL,
    LABEL VARCHAR2(255) NOT NULL,
    MOBILE_PHONE VARCHAR2(255) NOT NULL,
    FIXED_LINE VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(255) NOT NULL,
    REGISTRATION_DATE DATE NOT NULL,
    LICENSE_PLATE_ID NUMBER NOT NULL,
    CONSTRAINT FK_LICENSE_PLATE
    FOREIGN KEY (LICENSE_PLATE_ID) REFERENCES LICENSEPLATES(ID)
);

CREATE SEQUENCE MEMBERS_SEQ
START WITH 1
INCREMENT BY 1;


